* My dotfiles
It's my dotfiles.
Not anymore.


** Prerequisites
*** Emacs
- Ubuntu :: =sudo apt install emacs nodejs # because, nodejs is working LSP=
- Windows with [[https://scoop.sh/][scoop]] :: =scoop install emacs # because, nodejs is working LSP= [fn:emacs-windows]


*** Fish Shell
- Ubuntu :: =sudo apt install fish=

*** Vim
- Ubuntu :: =sudo apt install vim=
- Windows on scoop :: =scoop install vim=

** Expand My Dotfiles
- =.doom.d= directory include files :: Your =.doom.d= directory.
- =.config/fish= directory include files :: Your config about fish directory.
- =.*= s :: Maybe, just your home directory root.


** Post? Requisites
Post? You will complete this environment, Please done next sections after my dotfiles download and expanded.

*** Emacs
My Emacs environment dependent [[https://github.com/hlissner/doom-emacs][DOOM Emacs]].

#+BEGIN_SRC shell
mkdir ~/.doom.d; cd .doom.d; git init
git config core.sparsecheckout true; git remote add origin https://github.com/manzyun/dotfiles.git
echo .doom.d > .git/info/sparse-checkout # Appendix: You can use choice "| tee" alt ">" .
git pull origin main
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d; ~/.emacs.d/bin/doom install
#+END_SRC


*** Fish Shell
My Fish environmet dependent [[https://github.com/jorgebucaran/fisher][Fisher]]

#+BEGIN_SRC shell
mkdir -p ~/.config/fish; cd ~/.config/fish; git init
git config core.sparsecheckout true; git remote add origin https://github.com/manzyun/dotfiles.git
echo .config/fish > .git/info/sparse-checkout # Appendix: You can choice "| tee" alt ">" .
git pull origin main
curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
fisher
#+END_SRC


*** Vim
My Vim environment dependent [[https://github.com/junegunn/vim-plug][Vim plug]].

#+BEGIN_SRC shell
git init
git config core.sparsecheckout true; git remote add origin https://github.com/manzyun/dotfiles.git
echo .config/fish > .git/info/sparse-checkout # Appendix: You can use choice "| tee" alt ">" .
echo .vimrc > .git/info/sparse-checkout  # Appendix: You can choice "| tee" alt ">" .
git pull origin main
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#+END_SRC

and run =:PlugInstall= on Vim.


* Reference
- [[http://lambdalisue.hatenablog.com/entry/2013/06/23/071344][Vimを最強のPython開発環境にする2]]
- [[http://qiita.com/tadsan/items/9e6903e5db738f408292][(Emacs|Vim)初心者から脱出するためのなんやかんや - Qiita]]
- [[https://github.com/edc/bass#nvm][edc/bass]]


* Footnotes
- [fn:emacs-windows] Any installing tips in [[https://github.com/manzyun/dotfiles/tree/master/.doom.d][.doom.d/README.org]]
